### ISSUE TITLE
ITK / MHD / MetaIO

### ISSUE THREAD

**Issue by IngmarVoigt2** [MedicalUltrasound/Image3dAPI#159]
I would be great to have a simple executable that could convert any of the input Ultrasound data to a widely used open format such as e.g. https://vtk.org/Wiki/ITK/MetaIO/Documentation. The current API & backend brings quite some complexity due to the usage of COM and ATL (the choice of which certainly understandable to encapsulate proprietary parts). This may also mitigate limitations for cross platform usage #3

**Comment by forderud** [comment]
This project does not really address any specific file formats. Instead, it specifies an API for accessing 3D ultrasound data, regardless of underlying file format. The API is COM-based, so that it can be accessed easily from multiple programming languages, including C++, C# & Python.

Did you take a look at the Python sample code in https://github.com/MedicalUltrasound/Image3dAPI/blob/master/TestPython/TestPython.py?  It should be fairly simple to tweak this code to fit your needs.
