### ISSUE TITLE
TestViewer: Image doesn't always update on screen after opening multiple image files

### ISSUE THREAD

**Issue by forderud** [MedicalUltrasound/Image3dAPI#78]
Problem report by @mdickerson110 :
`Also I noticed another bug in the TestViewer. When I open up multiple images in a row without reloading the Loader, the images don’t always update. One way I saw to fix this was to automatically update the Loader on every new image. There’s probably a better solution, but one way or another this needs to addressed before the demo.`

**Comment by mdickerson110** [comment]
I tried testing your changes and was still getting the same issue. This led me to double check if the Philips File Loader was correctly removing the old data, and I realized it was not. So the issue is not with the Test Viewer. I will leave it to your discretion of you want to go ahead and merge your change or leave as it was before. Sorry for the misdirection!

**Comment by forderud** [comment]
I would prefer to still merge https://github.com/MedicalUltrasound/Image3dAPI/pull/79 if you're ok with that, so that we reduce risk of end-user confusion.

**Comment by mdickerson110** [comment]
Sounds good, thanks.
